### ISSUE TITLE
InputManager.__init__() got an unexpected keyword argument 'run_initial_rules_after_every_mutation'

### ISSUE THREAD

**Issue by XixianLiang** [ecnusse/Kea#17]
@XYIheng 
<img width="888" alt="image" src="https://github.com/user-attachments/assets/f5174f19-8715-4701-83f1-9a7c83357b53">

**Comment by XYIheng** [comment]
@XixianLiang 我没有碰到，这是怎么触发的？运行的哪个property?

**Comment by XixianLiang** [comment]
> @XixianLiang 我没有碰到，这是怎么触发的？运行的哪个property?

Already fixed. There are some merge conficts between me and @XiangchenShen . This is a deprecated arg.
